{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: services
  annotations:
    {{- $ingressClass := index .Values "ingress-nginx" "controller" "ingressClass" }}
    {{- if $ingressClass }}
    kubernetes.io/ingress.class: {{ $ingressClass }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #/api/aslan/project will be rewritten to /api/project before sending request to endpoint
    ingress.kubernetes.io/rewrite-target: /api/$2
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
  labels:
    {{- include "zadig.labels" . | nindent 4 }}
spec:
  {{- if .Values.tags.ingressController}}
  {{- if and $ingressClass (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $ingressClass }}
  {{- end }}
  {{- end }}
  {{- if .Values.endpoint.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.endpoint.FQDN }}
      secretName: {{ .Values.endpoint.tls.secretName }}
  {{- end }}
  rules:
  {{- if eq .Values.endpoint.type "FQDN" }}
  - host: {{ required ".Values.endpoint.FQDN is required for FQDN" .Values.endpoint.FQDN }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /api/aslan(/|$)(.*)
        {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: aslan
            port:
              number: {{ include "zadig.microservice.aslan.port" . }}
          {{- else }}
          serviceName: aslan
          servicePort: {{ include "zadig.microservice.aslan.port" . }}
          {{- end }}
      {{- if .Values.tags.enterprise }}
      - path: /api/aslanx(/|$)(.*)
        {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: aslanx
            port:
              number: {{ include "zadig.microservice.aslan-x.port" . }}
          {{- else }}
          serviceName: aslanx
          servicePort: {{ include "zadig.microservice.aslan-x.port" . }}
          {{- end }}
      {{- end }}
      - path: /api/podexec(/|$)(.*)
        {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: podexec
            port:
              number: {{ include "zadig.microservice.podexec.port" . }}
          {{- else }}
          serviceName: podexec
          servicePort: {{ include "zadig.microservice.podexec.port" . }}
          {{- end }}
